GET http://localhost:8000/api/persons
Accept: application/json

###
GET http://localhost:8000/api/persons/1
Accept: application/json

###
POST http://localhost:8000/api/persons
Content-Type: application/json

{
    "person_username": "John Doe",
    "person_password": "123456"
}

### login
POST http://localhost:8000/api/persons/login
Content-Type: application/json

{
    "person_username": "jdoe",
    "person_password": "password123"
}

###
PUT http://localhost:8000/api/persons/1
Content-Type: application/json

{
    "person_username": "John Moe",
    "person_password": "123456"
}

###
DELETE http://localhost:8000/api/persons/1
Accept: application/json
